# Copyright 2020-2025 Intel Corporation
# Licensed under the Apache License, Version 2.0

# pyright: reportUnusedImport=false, reportUnusedParameter=false, reportUnknownParameterType=false, reportMissingParameterType=false, reportUnknownVariableType=false, reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnusedVariable=false, reportImplicitStringConcatenation=false

"""Generate a throwaway pytest plugin that removes a bare `skipXPU` token
from one OpInfo's `decorators=[...]` in-memory, for the P7 non-editable-
install fallback in the `remove-xpu-skips` skill.

Why this exists
----------------
`remove-xpu-skips`' normal P7 removal edits
`common_methods_invocations.py` on disk under `--pytorch-folder`, then
re-runs pytest and expects the edit to take effect. That only works when
the target conda env's installed `torch` is an EDITABLE install pointing
at that exact checkout. When `torch` is a built wheel (or an editable
install of a *different* checkout), editing the checkout file never
reaches the interpreter that pytest actually imports -- the probe would
silently "pass" without validating anything, so Step 0b in that skill
refuses to edit the file and stops with `skip_not_editable_install`.

This script provides a fallback that works regardless of whether the
install is editable: instead of editing a file on disk, it emits a
pytest plugin module implementing `pytest_configure(config)`, which
pytest imports and runs during its configure phase -- strictly BEFORE
any test module is collected/imported. The hook walks the *running*
interpreter's `torch.testing._internal.common_methods_invocations.op_db`
list, finds the OpInfo matching `--op-info-name`, and removes the bare
`skipXPU` function reference from its `decorators` tuple in place (i.e.
by mutating the OpInfo object's attribute, not by editing any file).
Since OpInfo instances are shared singletons within one Python process
(any module that already holds a reference to the same list/object sees
the same mutation), this is visible to test_*.py files regardless of
import order, as long as it happens before collection -- which
`pytest_configure` guarantees.

The generated plugin is loaded via `pytest -p <module_name>` with
`PYTHONPATH` (or `--rootdir`-relative `sys.path` insertion) pointing at
its directory; it is never placed inside the checkout's test tree and
is not a `conftest.py` (so it never risks colliding with, or lingering
in, the actual test directory).

Scope: P7 only (bare `skipXPU` in `OpInfo.decorators=[...]`), per
`remove-xpu-skips`. Does NOT handle P8 (`DecorateInfo(...,
device_type='xpu', ...)` in `skips=(...)`) -- that pattern is out of
scope for this fallback.

This script NEVER edits `pytorch_folder`. It only writes the generated
plugin file to `--output`. The mutation it performs at pytest-run-time
is process-local and vanishes when that pytest process exits: nothing
persists to disk, so this is strictly a diagnostic/verification tool,
never a substitute for landing an actual source-code fix.
"""

import argparse
import json
import os
import sys


PLUGIN_TEMPLATE = '''\
# Auto-generated by remove-xpu-skips (P7 non-editable-install fallback).
# DO NOT COMMIT. DO NOT EDIT BY HAND -- regenerate via
# generate_op_db_override.py if the target OpInfo changes.
#
# Removes the bare `skipXPU` token from
# OpInfo({op_info_name!r}).decorators, in-memory, for the lifetime of this
# pytest process only. Nothing is written to disk; this never touches
# the installed torch package or the pytorch checkout. Loaded via:
#   pytest -p {module_name}
# with this file's directory on PYTHONPATH / sys.path.

OP_INFO_NAME = {op_info_name!r}

# Populated by pytest_configure so a later hook (or the test session
# itself, via -s output) can report whether a removal actually happened.
override_applied = False
override_note = ""


def pytest_configure(config):
    global override_applied, override_note
    import warnings

    try:
        import torch.testing._internal.common_methods_invocations as m
        from torch.testing._internal.common_device_type import skipXPU
    except Exception as exc:  # pragma: no cover - environment problem
        override_note = "import_failed: {{}}".format(exc)
        warnings.warn("op_db_override: " + override_note)
        return

    found_op = False
    removed = False
    for op in m.op_db:
        if op.name != OP_INFO_NAME:
            continue
        found_op = True
        if skipXPU in op.decorators:
            op.decorators = tuple(d for d in op.decorators if d is not skipXPU)
            removed = True

    if not found_op:
        override_note = "op_not_found: {{}} not present in op_db".format(
            OP_INFO_NAME
        )
        warnings.warn("op_db_override: " + override_note)
    elif not removed:
        override_note = (
            "no_skipxpu_token: {{}} found but decorators has no bare "
            "skipXPU (already removed, or gated by skipXPUIf/DecorateInfo "
            "instead of a bare skipXPU -- out of scope for this override)"
        ).format(OP_INFO_NAME)
        warnings.warn("op_db_override: " + override_note)
    else:
        override_applied = True
        override_note = "removed bare skipXPU from {{}}.decorators".format(
            OP_INFO_NAME
        )
'''


def slugify(op_info_name):
    s = op_info_name.replace(".", "_").replace("-", "_")
    s = "".join(ch if (ch.isalnum() or ch == "_") else "_" for ch in s)
    if s and s[0].isdigit():
        s = "_" + s
    return s


def main(argv=None):
    parser = argparse.ArgumentParser(
        description=(
            "Generate a throwaway pytest plugin that removes a bare "
            "skipXPU token from one OpInfo's decorators=[...] in-memory "
            "(P7 non-editable-install fallback for remove-xpu-skips)."
        )
    )
    parser.add_argument(
        "--op-info-name",
        required=True,
        help="OpInfo name, e.g. 'torch.ops.aten._flash_attention_forward'",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to write the generated plugin .py file",
    )
    args = parser.parse_args(argv)

    output_path = args.output
    if not output_path.endswith(".py"):
        print(
            "warning: --output should end in .py so it is importable; "
            "got: {}".format(output_path),
            file=sys.stderr,
        )

    output_dir = os.path.dirname(os.path.abspath(output_path))
    os.makedirs(output_dir, exist_ok=True)

    # pytest's -p flag imports the plugin by module name, which must match
    # the output file's stem (without .py) once its directory is on
    # PYTHONPATH/sys.path -- so the stem, not any name derived from
    # --op-info-name, is the single source of truth used both in the
    # generated header comment and in the reported usage example below.
    stem = os.path.splitext(os.path.basename(output_path))[0]

    content = PLUGIN_TEMPLATE.format(
        op_info_name=args.op_info_name,
        module_name=stem,
    )
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(content)

    result = {
        "op_info_name": args.op_info_name,
        "plugin_path": os.path.abspath(output_path),
        "plugin_dir": output_dir,
        "pytest_plugin_module": stem,
        "pytest_p_flag": "-p {}".format(stem),
        "usage_example": (
            'PYTHONPATH="{dir}:$PYTHONPATH" conda run --no-capture-output '
            "-n <conda_env> python -m pytest <test_file> -v "
            "-k \"<ClassName> and xpu and <op_short_name>\" "
            "-p {stem} --tb=short --no-header"
        ).format(dir=output_dir, stem=stem),
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
